### ISSUE TITLE
The initial password of user toor@localhost is incorrect

### ISSUE THREAD

**Issue by EthanLiu1991** [LabKey/Dockerfile#121]
Hello,
When I use the initial user 'toor@localhost' to login in LabKey, it shows incorrect password. But I confirm the initial password is right. And I also enable Chrome to allow insecure localhost.

Meanwhile, it shows the security policy has FALSE PlatformDeveloperPermission and TroubleshooterPermission.

Is the problem releation to the security policy?

![WechatIMG472](https://github.com/user-attachments/assets/1f4feac7-ed21-4ed7-bedd-09d9ffa4deb2)

**Comment by labkey-mohara** [comment]
Hi Ethan: 

Thanks for reaching out. It sounds like you used this option, but may have missed the note about password setting:

> [You can optionally bypass the initial user creation "wizard" by creating an initial user using the following environment variables. At time of writing, there is no way to set the initial user's password. Assuming valid SMTP configuration, the "forgot password" link can be used to accomplish this.](https://github.com/LabKey/Dockerfile/blob/develop/README.md#:~:text=You%20can-,optionally%20bypass,-the%20initial%20user)

If you don't have SMTP working to reset the password, I'd recommend retrying without those variables and using the wizard to create that first user account and password directly in the UI instead.

[Please contact us via this link if you need further assistance getting started with LabKey](https://www.labkey.com/about/contact-us/).

--Molly
